### ISSUE TITLE
code block in markdown is rendered simply as <code> in post

### ISSUE THREAD

**Issue by MaiMee1** [KooCook/koocook-dj#10]
` ``` ` is supposed to denote a code block which is normally a `<pre>` and a `<code>` tag, but the current rendering results in just a `<code>` tag instead.

**Comment by th-bunratta** [comment]
It has been fixed in https://github.com/KooCook/koocook-dj/commit/31d17592716050042d0484180f811dc107aff13c.
Thanks for the report.
