### ISSUE TITLE
Issues with 'Side by Side view' for posts

### ISSUE THREAD

**Issue by MaiMee1** [KooCook/koocook-dj#24]
- 'Side by Side' hides the first two rows.

- No useful guides or cues (as in nothing telling the user what to do) for telling users how to get back to normal view.

- There are **false** guides causing even more confusion. (Says 'Crtl+P' to toggle preview, doesn't actually do that; same with other short-keys)

To reproduce the first issue, Fill in the posts with some characters. Notice that it only shows lines after the second in 'Side be Side'.

**Comment by th-bunratta** [comment]
Removed in https://github.com/KooCook/koocook-dj/commit/d2103db3b272381a2a15ab8f759cad22e14b5016
