### ISSUE TITLE
Issues with Post stream's 'Trending'

### ISSUE THREAD

**Issue by MaiMee1** [KooCook/koocook-dj#26]
- Post text aren't rendered correctly. Markdowns are rendered, but the html are escaped and aren't evaluated.

**Comment by th-bunratta** [comment]
This is intentional by default to prevent malicious attempts.

**Comment by MaiMee1** [comment]
I meant. The markdown was processed and changed to html, but then shows up as actual HTML text. The original post the user typed in has no HTML.

**Comment by th-bunratta** [comment]
Okay, I see. Fixed in https://github.com/KooCook/koocook-dj/pull/29.
