### ISSUE TITLE
Changing "Sort by" in "Recipe Search Results" resets query params

### ISSUE THREAD

**Issue by MaiMee1** [KooCook/koocook-dj#34]
Search query is lost when "Sort by" is changed. This shouldn't be standard behaviour users expect.

To reproduce, search with a query, then try changing the "Sort by" category to something other than the default "Date published".

**Comment by th-bunratta** [comment]
Fixed in https://github.com/KooCook/koocook-dj/commit/fd8ac65d976797576ee71f43b1e9d23637e244bb, but still unmerged

This branch also introduces a new query ruleset system.
